config/routes.rb
Rails.application.routes.draw do
  get 'portscans/index'

  root 'welcome#index'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/newvul', to: 'vuls#new'
  post '/newvul', to: 'vuls#create'
  get 'search/index'
  get 'search', to: 'search#index'
  resources :users
  resources :vuls
  resources :portscans
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/portscans_controller.rb
class PortscansController < ApplicationController
  
  def index
    @scans = Port.all
  end

  def new
    @portscan = Port.new
  end
  
  def create
    @portscan = Port.new(scan_params)
    @portscan.status = 0
    if @portscan.save
      Portscanasync.perform_async(@portscan.id)
      redirect_to portscan_path(@portscan)
    else
      render 'new'
    end
  end
  
  def show
    @scan = Port.find(params[:id])
    @result = redis.get(@scan.id)
  end

	def destroy
		@scan = Port.find(params[:id])
		FileUtils.rm Dir.glob(PortScan.configuration.output_dir + @scan.id.to_s + '.*')
		redis.del @scan.id
		@scan.destroy
		redirect_to portscans_path
	end

  private
    def scan_params
      params.require(:port).permit(:title, :target)
    end
    
    def redis
      @redis ||= Redis.new
    end

end

app/helpers/portscans_helper.rb
module PortscansHelper
end

app/views/portscans/index.html.erb
<% provide(:title, "All Port Scan") %>
<p>
<h1>Listing Scans</h1>

<table class="table">
<%= link_to 'New Scan', new_portscan_path %>
<tr>
<th>Title</th>
<th>Target</th>
<th>Status</th>
<th>Show</th>
<th>Destroy</th>
</th>
<% @scans.each do |scan| %>
	<tr>
	<th><%= scan.title %></th>
	<th><%= scan.target %></th>
	<th><% if scan.status == 0 %>
  		Queued
		<% elsif scan.status == 1 %>
		Running
		<% else %>
		Finished
		<% end %>
	</th>
	<th><%= link_to 'Show', portscan_path(scan) %> </th>
	<th>
	<% if scan.status == 2 %>
		<%= link_to 'Destroy', portscan_path(scan),
		method: :delete,
		data: { confirm: 'Are you sure?' } %>
	<% else %>
		Destroy
	<% end %> </th>
	</tr>
<% end %>
</table>

app/views/portscans/new.html.erb
<% provide(:title, "New Port Scan") %>

<h1>New Scan</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(@portscan, url: portscans_path ) do |f| %>
            <%= render 'shared/error_messages', object: f.object %>

            <%= f.label :title %>
            <%= f.text_field :title, class: 'form-control' %>

            <%= f.label :target %>
            <%= f.text_field :target, class: 'form-control' %>

            <%= f.submit "Start scan", class: "btn btn-primary" %>

        <% end %>

        <p>New Scan? <%= link_to "Back", portscans_path %></p>
    </div>
</div>

app/views/portscans/show.html.erb
<p>
<strong>Title:</strong>
<%= @scan.title %>
</p>
<p>
<strong>Target:</strong>
<%= @scan.target %>
</p>
<p>
<strong>Status</strong>

<% if @scan.status == 0 %>
  Queued
<% elsif @scan.status == 1 %>
  Running
<% else %>
  Finished
<% end %>
</p>

<p>
<% if @result and File.exist? @result %>
  <p>
  <% file = File.read(@result) %>
  <% scans = JSON.parse(file) %>
  <% id = 0 %>
  <% scans.each do |scan| %>
    <table>
    <tr><td>IP Address:</td><td> <%= scan['ip'] %></td></tr>
    <tr><td>Status:</td><td> <%= scan['status']['state'] %></td></tr>
    <tr><td>MAC:</td><td> <%= scan['mac'] %></td></tr>
    <tr><td>Vendor:</td><td> <%= scan['vendor'] %></td></tr>
    <tr><td>Hostnames:</td><td>
    <% scan['hostnames'].each do |h| %>
      <%= h['name'] %>
    <% end %>
    </td></tr>
    </table>
    Operation System:
    <% if scan['cpes'] %>
      <% scan['cpes'].each do |(cpe,cves)| %>
        <% if cves.count > 0 %>
          <% cpe_id = cpe.gsub(/\.|\/|:/, '_') + id.to_s %>
          <a data-toggle="collapse" href="#<%= cpe_id %>">
          <%= cpe %>
          </a>
        <% else %>
          <%= cpe %>
        <% end %>
      <% end %> 
      <% scan['cpes'].each do |(cpe,cves)| %>
        <% if cves.count > 0 %>
          <% cpe_id = cpe.gsub(/\.|\/|:/, '_') + id.to_s %>
          <div id="<%= cpe_id %>" class="collapse">
          <%= cpe %>
          <% cves.each do |cve| %>
            <div>
            <%= link_to cve['id'], cve['idurl'] %>
            <% if cve['impact'] %>
              <% if cve['impact']['confidentiality'] == "COMPLETE" %>
                <span style="color:red" title="Confidentiality Impact: COMPLETE">
              <% elsif cve['impact']['confidentiality'] == "PARTIAL" %>
                <span style="color:orange" title="Confidentiality Impact: PARTIAL">
              <% elsif cve['impact']['confidentiality'] == "NONE" %>
                <span style="color:green" title="Confidentiality Impact: NONE">
              <% else %>
                <span style="color:black">
              <% end %>
              C
              </span>
              <% if cve['impact']['integrity'] == "COMPLETE" %>
                <span style="color:red" title="Integrity Impact: COMPLETE">
              <% elsif cve['impact']['integrity'] == "PARTIAL" %>
                <span style="color:orange" title="Integrity Impact: PARTIAL">
              <% elsif cve['impact']['integrity'] == "NONE" %>
                <span style="color:green" title="Integrity Impact: NONE">
              <% else %>
                <span style="color:black">
              <% end %>
              I
              </span>
              <% if cve['impact']['availability'] == "COMPLETE" %>
                <span style="color:red" title="Availability Impact: COMPLETE">
              <% elsif cve['impact']['availability'] == "PARTIAL" %>
                <span style="color:orange" title="Availability Impact: PARTIAL">
              <% elsif cve['impact']['availability'] == "NONE" %>
                <span style="color:green" title="Availability Impact: NONE">
              <% else %>
                <span style="color:black">
              <% end %>
              A
              </span>
            <% end %>
            <% if cve['access'] %>
              <%= image_tag(cve['access']['vector'] + ".png", width: "20", height: "20", title: "ACCESS: " + cve['access']['vector']) %>
            <% end %>
            <% if cve['edb'] %>
              <%= link_to image_tag("edb.png", width: "20", height:"20", title: "Exploit-DB"), cve['edb'] %>
            <% end %>
            <% if cve['msf'] %>
              <%= link_to image_tag("msf.png", width: "20", height:"20", title: "Metasploit"), cve['msf'] %>
            <% end %>
            </div>
          <% end %>
        <% end %>
        </div>
      <% end %>
    <% else %>
      System not reconized
    <% end %>
    <% id = id+1 %>
    <% if scan['ports'] %>
      <table class="table table-bordered">
      <thead>
      <tr><td>Service</td><td>Banner</td><td>Port/Protocol</td><td>Status</td><td>CPEs</td></tr>
      </thead>
      <% scan['ports'].each do |port| %>
        <tr>
        <td><%= port['name'] %></td>
        <td><%= port['product'] %> <%= port['version'] %> <%= port['extra_info'] %></td>
        <td><%= port['port'] %>/<%= port['protocol'] %></td>
        <td><%= port['state'] %></td>
        <td>
        <% port['cpes'].each do |(cpe,cves)| %>
          <% if cves.count > 0 %>
            <% cpe_id = cpe.gsub(/\.|\/|:/, '_') + id.to_s %>
            <a data-toggle="collapse" href="#<%= cpe_id %>">
            <%= cpe %>
            </a>
          <% else %>
            <%= cpe %>
          <% end %>
        <% end %>
        </td>
        </tr>
        <tr>
        <td colspan="5">
        <% port['cpes'].each do |(cpe,cves)| %>
          <% if cves.count > 0 %>
            <% cpe_id = cpe.gsub(/\.|\/|:/, '_') + id.to_s %>
            <div id="<%= cpe_id %>" class="collapse">
            <%= cpe %>
            <% cves.each do |cve| %>
              <div>
              <%= link_to cve['id'], cve['idurl'] %>
              <% if cve['impact'] %>
                <% if cve['impact']['confidentiality'] == "COMPLETE" %>
                  <span style="color:red" title="Confidentiality Impact: COMPLETE">
                <% elsif cve['impact']['confidentiality'] == "PARTIAL" %>
                  <span style="color:orange" title="Confidentiality Impact: PARTIAL">
                <% elsif cve['impact']['confidentiality'] == "NONE" %>
                  <span style="color:green" title="Confidentiality Impact: NONE">
                <% else %>
                  <span style="color:black">
                <% end %>
                C
                </span>
                <% if cve['impact']['integrity'] == "COMPLETE" %>
                  <span style="color:red" title="Integrity Impact: COMPLETE">
                <% elsif cve['impact']['integrity'] == "PARTIAL" %>
                  <span style="color:orange" title="Integrity Impact: PARTIAL">
                <% elsif cve['impact']['integrity'] == "NONE" %>
                  <span style="color:green" title="Integrity Impact: NONE">
                <% else %>
                  <span style="color:black">
                <% end %>
                I
                </span>
                <% if cve['impact']['availability'] == "COMPLETE" %>
                  <span style="color:red" title="Availability Impact: COMPLETE">
                <% elsif cve['impact']['availability'] == "PARTIAL" %>
                  <span style="color:orange" title="Availability Impact: PARTIAL">
                <% elsif cve['impact']['availability'] == "NONE" %>
                  <span style="color:green" title="Availability Impact: NONE">
                <% else %>
                  <span style="color:black">
                <% end %>
                A
                </span>
              <% end %>
              <% if cve['access'] %>
                <%= image_tag(cve['access']['vector'] + ".png", width: "20", height: "20", title: "ACCESS: " + cve['access']['vector']) %>
              <% end %>
              <% if cve['edb'] %>
                <%= link_to image_tag("edb.png", width: "20", height:"20", title: "Exploit-DB"), cve['edb'] %>
              <% end %>
              <% if cve['msf'] %>
               <%= link_to image_tag("msf.png", width: "20", height:"20", title: "Metasploit"), cve['msf'] %>
              <% end %>
              </div>
            <% end %>
          <% end %>
          </div>
        <% end %>
        </td>
        </tr>
        <% id = id+1 %>
      <% end %>
      </table>
    <% end %>
  <% end %>
<% end %>
<p>
<%= link_to 'Back', portscans_path %>
</p>