config/routes.rb
Rails.application.routes.draw do
  get 'portscans/index'

  root 'welcome#index'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/newvul', to: 'vuls#new'
  post '/newvul', to: 'vuls#create'
  get 'search/index'
  get 'search', to: 'search#index'
  resources :users
  resources :vuls
  resources :portscans
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/vul.rb
class Vul < ApplicationRecord
	include Elasticsearch::Model
	include Elasticsearch::Model::Callbacks

	index_name 'dscan'
	document_type 'vuls'

	mount_uploader :file, PocUploader
	belongs_to :user
	validates :user_id, presence: true
	belongs_to :type, class_name: "Vultype"
	#validates :type_id, presence: true
	belongs_to :level, class_name: "Vullevel"
	#validates :level_id, presence: true

	default_scope { order(created_at: :desc) }

	mapping do
		indexes :name, type: 'string'
		indexes :description, type: 'string'
		indexes :search_key, type: 'string'
	end

	def as_indexed_json(_options = {})
	{
		name: self.name,
		description: self.description,
		search_key: self.search_key,
	}
	end
	
end

app/models/vultype.rb
class Vultype < ApplicationRecord
	has_many :vuls, class_name: "Vul", foreign_key: "type_id"
end

app/controllers/vuls_controller.rb
class VulsController < ApplicationController
	before_action :logged_in_user, only: [:create, :destroy]
	before_action :corrent_user, only: :destroy

	def index
		@vuls = Vul.paginate(page: params[:page], per_page: 9)
	end

	def show
		@vul = Vul.find(params[:id])
	end

	def new
		@vul = Vul.new
		@vultype = Vultype.all
		@vullevel = Vullevel.all
	end

	def create
		vul = current_user.vuls.build(vul_params)
		if params[:vul][:format] == "json"
			file = save_json_poc(params[:poc],vul)
			puts file
			File.open(file) do |f|
				vul.file = f
			end
		end
		if vul.save
			flash[:success] = "New vulnerability created!"
			redirect_to vul
		else
			render newvul_path
		end
	end

	def edite
	end

	def update
	end

	def destroy
		@vul.destroy
		flash[:success] = "Vul deleted"
		redirect_to request.referrer || root_url
	end
  
	  private

	    #params security
	    def vul_params
	      params.require(:vul).permit(:name, :description, :search_key,
	                                    :type_id, :level_id, :file, :format )
	    end

		def corrent_user
			@vul = current_user.vuls.find_by(id: params[:id])
			redirect_to root_url if @vul.nil?
		end
		

		def save_json_poc(plugin,vul)
			poc = {}
			poc[:info] = vul.description
			poc[:name] = vul.name
			poc[:search_key] = vul.search_key
			poc[:type] = vul.type.typename
			poc[:level] = vul.level.levelname
			poc[:plugin] = {}
			poc[:plugin][:method] = plugin[:method]
			poc[:plugin][:getdata] = plugin[:getdata]
			poc[:plugin][:postdata] = plugin[:postdata]
			poc[:plugin][:keyword] = plugin[:keyword]
			filename = Time.now.to_a[0..-3].join + rand(10000).to_s+'.json'
			file = "/tmp/mypoc/"+filename
			File.open(file, "w+") do |f|
				f.write(JSON.pretty_generate(poc))
			end
			return file
		end

end

app/helpers/vuls_helper.rb
module VulsHelper

	def createcode(file)
		return if file.nil?
		code = File.read(file)
		if File.extname(file) == '.rb'
			CodeRay.scan(code, :ruby).div(:tab_width => 2).html_safe
		else
			CodeRay.scan(code, :json).div(:tab_width => 2).html_safe
		end
	end


	

end

app/views/vuls/_vul.html.erb
<div class="list-group col-md-4">
  <a href="<%= vul_path(vul) %>" class="list-group-item active">
    <h4 class="list-group-item-heading"><button type="button" class="btn btn-info btn-xs">Vulname: </button>&nbsp&nbsp<%= vul.name %></h4>
    <p class="list-group-item-text"><button type="button" class="btn btn-info btn-xs">Author: </button>&nbsp&nbsp<%= vul.user.name %></p>
    <button type="button" class="btn btn-info btn-xs">Description: </button>
    <p class="list-group-item-text"><%= vul.description %></p>
    <p class="list-group-item-text"><button type="button" class="btn btn-info btn-xs">Update_at: </button>&nbsp&nbsp<%= vul.updated_at %></p>
  </a>
</div>

app/views/vuls/index.html.erb
<% provide(:title, "vuldb") %>



<%= render @vuls %>




<%= will_paginate %>

app/views/vuls/new.html.erb
<% provide(:title, "VulDB") %>

<h1>This can commit a new vulnerability</h1>

<div class="bs-example">
<button type="button" class="btn btn-success btn-lg" data-toggle="modal" data-target="#exampleModal1" data-whatever="@mdo">File</button>
<button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#exampleModal2" data-whatever="@mdo">Json</button>
<div class="modal fade" id="exampleModal1" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
<div class="modal-dialog" role="document">
    <div class="modal-content">
     <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel">New POC</h4>
      </div>
         <div class="modal-body">
            <%= form_for(@vul, url: newvul_path ) do |f| %>
                <%= render 'shared/error_messages', object: f.object %>

                <%= f.hidden_field :format, :value=>"file" %>

                <%= f.label :name %>
                <%= f.text_field :name %>

                <%= f.label :description %>
                <%= f.text_field :description %>
                
                <%= f.label :search_key %>
                <%= f.text_field :search_key %>
                
                <%= f.label :type %>
                <%= f.select :type_id, @vultype.collect { |t| [t.typename, t.id] }, {}, { :class => 'form-control' } %>

                <%= f.label :level %>
                <%= f.select :level_id, @vullevel.collect { |t| [t.levelname, t.id] }, {}, { :class => 'form-control' } %>

                <%= f.label :poc %>
                <%= f.file_field :file, class: "form-control" %>
                <%= f.hidden_field :file_cache %>
                <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            <% end %>
        </div>
</div>
</div>
</div>

<div class="modal fade" id="exampleModal2" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
<div class="modal-dialog" role="document">
    <div class="modal-content">
     <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel">New POC</h4>
      </div>
         <div class="modal-body">
            <%= form_for(@vul, url: newvul_path, :html => { :class => "form-horizontal" } ) do |f| %>
                <%= render 'shared/error_messages', object: f.object %>

                <%= f.hidden_field :format, :value=>"json" %>
                <%= f.label :name %>
                <%= f.text_field :name %>

                <%= f.label :description %>
                <%= f.text_field :description %>
                
                <%= f.label :search_key %>
                <%= f.text_field :search_key %>
                
                <%= f.label :type %>
                <%= f.select :type_id, @vultype.collect { |t| [t.typename, t.id] }, {}, { :class => 'form-control' } %>

                <%= f.label :level %>
                <%= f.select :level_id, @vullevel.collect { |t| [t.levelname, t.id] }, {}, { :class => 'form-control' } %>

                <div class="form-group">
                <%= select "poc", :method, ["GET", "POST"], {}, { :class => 'col-sm-2 control-label' } %>
                <div class="col-sm-9">
                <%= text_field "poc", :getdata,  { :class => "form-control" }%>
                </div>
                </div>

                <%= text_area "poc", :postdata, { :placeholder =>"Post data...", :class => 'form-control' } %>
                <div class="form-group">
                <%= label "poc", :keyword, { :class => "col-sm-2 control-label" } %>
                 <div class="col-sm-5">
                <%= text_field "poc", :keyword, { :class => "form-control" } %>
                </div>
                </div>
                <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            <% end %>
        </div>
</div>

</div>

app/views/vuls/show.html.erb
<% provide(:title, @vul.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @vul.name %>
      </h1>
      <ul>
      	<li><%= @vul.description %></li>
      	<li><%= @vul.search_key %></li>
      	<li><%= @vul.type.typename %></li>
      	<li><%= @vul.level.levelname %></li>
      	<li><%= @vul.user.name %></li>
      </ul>
    </section>
    <%= createcode(@vul.file.current_path) %>
  </aside>

</div>